### ISSUE TITLE
ask "WIDP IT Team" to clean-up from the database in NHWA modules the incorrect apostrophes

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#710]
the incorrect apostrophes appears 3 times. . The character (special aprostrophe "’") and use normal apostrophes instead.

![image](https://user-images.githubusercontent.com/2181866/98807493-00bc7600-241b-11eb-8c44-167731adf0be.png)

**Comment by SferaDev** [comment]
Spoke with @idelcano this morning. He already cleansed the items listed on the original description as of yesterday, and plans to review the full database for the character during the following days.

I found out there're 72 org units affected and some CO and COC. We can quickly traverse identifiable properties with the following call: ``/api/metadata.json?filter=identifiable:ilike:%E2%80%99``.

Once he revisits all the usages I will do a quick review to verify the task is completed.

**Comment by SferaDev** [comment]
Investigated with @tokland, it is indirectly resolved on 2.34, so even though is good to have the database clean of apostrophes now so that official packages are properly built we might not need to worry much about it as the 2.34 update is imminent. @adrianq What do you think?

**Comment by tokland** [comment]
Out of curiosity, I set up the scripts to do a `git bisect run`, with this result (read "bad" as "good", in this case):

```
dabffa881cee3b42ec361053354ccc7eec6d4644 is the first bad commit
```

So the fix (https://github.com/dhis2/dhis2-core/commit/dabffa881cee3b42ec361053354ccc7eec6d4644) was a (unforeseen?) side-effect of updating `spring`. This issue seems related to the problem: https://github.com/spring-projects/spring-framework/issues/24123

**Comment by SferaDev** [comment]
> Out of curiosity, I set up some scripts to do a `git bisect run` between 2.33 and 2.34 (it may come in useful, in the future), and this was the result (read "bad" as "good", in this case):
> 
> ```
> dabffa881cee3b42ec361053354ccc7eec6d4644 is the first bad commit
> ```
> 
> So the fix ([dhis2/dhis2-core@dabffa8](https://github.com/dhis2/dhis2-core/commit/dabffa881cee3b42ec361053354ccc7eec6d4644)) was simply a (unforeseen?) side-effect of updating `spring`. This issue seems related to the problem: [spring-projects/spring-framework#24123](https://github.com/spring-projects/spring-framework/issues/24123)

Awesome! I had in the past another idea conceptually similar to this one. It would consist of a bot that launched a docker on each DHIS2 core development branch that traversed a list of known bugs we had found (maybe stored as issues in our know-how). Each bug would have a code snippet that reproduced a bug with exit 0/1 error code and once it stopped failing it updated the online issue telling us it has been fixed on upstream, so that we can know the exact commit + probably a JIRA ticker + the ability to ask for a backport asap.

Yours is almost the inverse concept as it's a backtracking technique to find an already fixed bug in time.

Maybe we should mention this in our next weekly meeting, it's not much infra time and could be really helpful.

**Comment by tokland** [comment]
> telling us it has been fixed on upstream, so that we can know the exact commit

So cool :)

**Comment by adrianq** [comment]
Guys, great job! I agree we can consider this as solved for WHO. I am a bit more concerned with MSF now as they have just moved to 2.33. If I got you right, this bug still happens in 2.33 and they don't have any plan to backport the fix (I understand a spring update is not something you would backport). MSF, in principle, is not gonna use the package feature but just the event sync so we should be fine. Anyway, let's keep an eye on this...
